# Generated by Django 4.0.3 on 2022-04-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Event resolved')], max_length=255)),
                ('info', models.CharField(max_length=1000)),
                ('status_changed_by', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
