# Generated by Django 4.0.3 on 2022-04-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='status_changed_by',
        ),
    ]
