# Generated by Django 4.0.3 on 2022-04-04 19:38

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('company', models.CharField(max_length=255, unique=True)),
                ('id', models.UUIDField(default=uuid.UUID('3b8fc3a5-c9d5-4679-8110-901b02f11872'), editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
