# Generated by Django 4.0.3 on 2022-04-02 19:57

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('company', models.CharField(max_length=255, unique=True)),
                ('id', models.UUIDField(default=uuid.UUID('006486f2-81ba-47c8-a3ef-749663aa62fc'), editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
    ]
