# Generated by Django 4.0.3 on 2022-04-06 13:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='url',
            new_name='url_message',
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab03ad31-b1d4-477b-8437-8e19248903c3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
