# Generated by Django 4.0.3 on 2022-04-02 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e0950fd-03d7-4ca5-bae0-b9d2c2f91879'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
