# Generated by Django 4.0.3 on 2022-04-07 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_url_client_url_message_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9cf30dd3-eae2-459a-ae35-4a0ac83f837e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
