# Generated by Django 4.0.3 on 2022-04-07 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a262aef6-5982-4cc1-ad2b-4f618f080f0a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
