# Generated by Django 4.0.3 on 2022-04-13 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b7e31574-0fab-4630-8164-c5593783dada'), editable=False, primary_key=True, serialize=False),
        ),
    ]
