# Generated by Django 4.0.3 on 2022-04-03 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3dbdfbfc-7ae7-415c-b795-0dddee7f0ad9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
