# Generated by Django 4.0.3 on 2022-04-07 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f2179627-2360-48d3-b4cf-7a0ce9ff782d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
