# Generated by Django 4.0.3 on 2022-04-02 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.UUIDField(default=uuid.UUID('da6d7864-a683-4028-b56c-0bd4963cd696'), editable=False, primary_key=True, serialize=False),
        ),
    ]
