# Generated by Django 4.0.3 on 2022-04-04 19:38

from django.db import migrations, models
import django.db.models.deletion
import stage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f9972b9b-3ec5-4f73-ab09-655dd2ff6d73'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', stage.models.OrderField(blank=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='board.board')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
