# Generated by Django 4.0.3 on 2022-04-03 16:23

from django.db import migrations, models
import django.db.models.deletion
import stage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a843702e-be27-4963-84e7-d1ad7ca9654b'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', stage.models.OrderField(blank=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='board.board')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
