# Generated by Django 4.0.3 on 2022-04-07 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7d50432-c396-461d-bf4f-4ec5dbcb3c22'), editable=False, primary_key=True, serialize=False),
        ),
    ]
