# Generated by Django 4.0.3 on 2022-04-02 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93abe58f-e771-4c50-9282-65f59c153c51'), editable=False, primary_key=True, serialize=False),
        ),
    ]
