# Generated by Django 4.0.3 on 2022-04-03 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab91f351-1447-45fc-8ccd-74c1206a97dc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
