# Generated by Django 4.0.3 on 2022-04-04 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0002_alter_stage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8c86213-d179-4a24-8127-b678cd0ac432'), editable=False, primary_key=True, serialize=False),
        ),
    ]
