# Generated by Django 4.0.3 on 2022-04-03 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e05c7199-e296-45f9-b70c-a79c9f41ced3'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('members', models.ManyToManyField(related_name='teams', to='staff.staff')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
