# Generated by Django 4.0.3 on 2022-04-04 19:38

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d3d2129e-92ba-431c-90e1-2ef968843698'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
