# Generated by Django 4.0.3 on 2022-04-02 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('59fbca54-1b7c-4cf3-9e7c-f777b32b543e'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('members', models.ManyToManyField(related_name='teams', to='staff.staff')),
            ],
        ),
    ]
