# Generated by Django 4.0.3 on 2022-04-03 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.UUID('11a69740-aaa5-4f00-98bb-3d0da75d5ce6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
