# Generated by Django 4.0.3 on 2022-04-07 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ba78eff-7f6b-43e6-b431-09cb47eba426'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
