# Generated by Django 4.0.3 on 2022-04-04 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2673b060-9d9c-4ed0-b5c0-a54d61c2405f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
