# Generated by Django 4.0.3 on 2022-04-04 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e89e165d-b8d1-40a1-bd57-fb8b73ca0092'), editable=False, primary_key=True, serialize=False),
        ),
    ]
