# Generated by Django 4.0.3 on 2022-04-04 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('board', '0001_initial'),
        ('client', '0001_initial'),
        ('team', '0001_initial'),
        ('stage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('71c05414-8535-4b32-ad8b-56e7794bdd64'), editable=False, primary_key=True, serialize=False)),
                ('signature', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Event resolved')], default='new', max_length=255)),
                ('functionality', models.CharField(blank=True, choices=[('accountancy', 'Accountancy'), ('people', 'People'), ('production', 'Production'), ('products', 'Products'), ('warehouse', 'Warehouse'), ('report', 'Report'), ('transport', 'Transport'), ('orders_and_complaints', 'Orders and complaints')], max_length=255)),
                ('subject', models.CharField(choices=[('feature', 'I need a new feature'), ('help', 'I need help'), ('remark', 'I have remarks about application'), ('error', 'Bug in application')], max_length=255)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=255)),
                ('label', models.CharField(blank=True, choices=[('bug', 'Bug'), ('feature', 'Feature'), ('important', 'Important'), ('critical', 'Critical')], max_length=255)),
                ('description', models.CharField(default='', max_length=500)),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('is_assana_integrated', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='application.application')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='board.board')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='client.client')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='stage.stage')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='team.team')),
            ],
        ),
    ]
