# Generated by Django 4.0.3 on 2022-04-02 20:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0002_alter_stage_id'),
        ('team', '0002_alter_team_id'),
        ('staff', '0002_alter_staff_id'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6c850f53-2941-46de-8fd2-6fbeec6e2412'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='stage.stage'),
        ),
        migrations.AlterField(
            model_name='event',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='team.team'),
        ),
    ]
