# Generated by Django 4.0.3 on 2022-04-05 10:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_id'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='board.board'),
        ),
        migrations.AlterField(
            model_name='event',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb93e97a-e214-4257-89d1-c3509e9eb2c5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
