# Generated by Django 4.0.3 on 2022-04-07 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_id_alter_event_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('012b5ebf-ad4b-4a63-a652-81244c2d7f39'), editable=False, primary_key=True, serialize=False),
        ),
    ]
