# Generated by Django 4.0.3 on 2022-04-13 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0005_alter_event_id_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='course',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='client.client'),
        ),
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d93987f7-6cb4-4f23-b42b-43b20ed6f216'), editable=False, primary_key=True, serialize=False),
        ),
    ]
