# Generated by Django 4.0.3 on 2022-04-14 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_course_options_course_client_course_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f368ac1c-29eb-4c28-bb0d-cfd6127bfc57'), editable=False, primary_key=True, serialize=False),
        ),
    ]
