# Generated by Django 4.0.3 on 2022-04-03 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d537409c-3bc5-4d0c-ab05-bf01c0a49ff6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
