# Generated by Django 4.0.3 on 2022-04-07 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('754c68aa-fe3d-4ba8-a7d5-bd35bd56c02d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
