# Generated by Django 4.0.3 on 2022-04-03 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a365173-fdda-41ef-abfa-4024ab9c61ee'), editable=False, primary_key=True, serialize=False),
        ),
    ]
