# Generated by Django 4.0.3 on 2022-04-03 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f63ed2b4-9665-4142-9100-48ecde1f84ca'), editable=False, primary_key=True, serialize=False),
        ),
    ]
