# Generated by Django 4.0.3 on 2022-04-03 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.UUIDField(default=uuid.UUID('99e3f47a-e558-4e87-b80d-8efb515e3262'), editable=False, primary_key=True, serialize=False),
        ),
    ]
