# Generated by Django 4.0.3 on 2022-04-05 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.UUIDField(default=uuid.UUID('11cf1385-bf33-4790-a6b2-3ba4d4fe92e0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
