# Generated by Django 4.0.3 on 2022-04-04 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6dcc6033-44f6-42fb-ad87-c6212f4f0ca7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
