# Generated by Django 4.0.3 on 2022-04-04 19:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a076e47c-dfb9-4109-bc50-91fb27354d15'), editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='event.event')),
            ],
        ),
    ]
