# Generated by Django 4.0.3 on 2022-04-07 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('42323d39-f96b-4f50-8c30-6e5157086f1d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
