# Generated by Django 4.0.3 on 2022-04-07 12:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_id'),
        ('consultation', '0002_alter_consultation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='event.event'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4ceb06c-c71e-4af2-b20c-9fce11368222'), editable=False, primary_key=True, serialize=False),
        ),
    ]
