# Generated by Django 4.0.3 on 2022-04-07 13:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_id'),
        ('consultation', '0003_alter_consultation_event_alter_consultation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='client.client'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eca70d07-d2e3-4ea4-8ea9-8f4202fc006e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
